server:
  port: 8081

file:
  storage:
    location: file-storage

spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 1MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver